version: "3.8"

services:

  api_gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: unless-stopped
    networks:
      - mon-network
    ports:
      - "5000:5000"

  card_app:
    build:
      context: ./card-service
      dockerfile: Dockerfile
    container_name: card-service
    command: sh -c "npx prisma generate && npm run dev"
    restart: unless-stopped
    networks:
      - mon-network
    depends_on:
      - card_db
    environment:
      DATABASE_URL: postgres://${CARD_PGUSER}:${CARD_PGPASSWORD}@card_db:5433/${CARD_PGDATABASE}
    ports:
      - "5002:5002"

  card_db:
    image: postgres:15
    container_name: card_pgdb
    restart: unless-stopped
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: ${CARD_PGUSER}
      POSTGRES_PASSWORD: ${CARD_PGPASSWORD}
      POSTGRES_DB: ${CARD_PGDATABASE}
    networks:
      - mon-network
    volumes:
      - card-local_pgdata:/var/lib/postgresql/data

  card_pgadmin:
    image: dpage/pgadmin4
    container_name: card-pgadmin4
    restart: unless-stopped
    ports:
      - "6888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: card@card.card
      PGADMIN_DEFAULT_PASSWORD: card
    volumes:
      - card-pgadmin-data:/var/lib/pgadmin
    networks:
      - mon-network
    depends_on:
      - card_db

  user_app:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    command: sh -c "npx prisma generate && npm run dev"
    networks:
      - mon-network
    depends_on:
      - user_db
    environment:
      DATABASE_URL: postgres://${USER_PGUSER}:${USER_PGPASSWORD}@user_db:5432/${USER_PGDATABASE}
    ports:
      - "5001:5001"

  user_db:
    image: postgres:15
    container_name: user_pgdb
    restart: unless-stopped
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: ${USER_PGUSER}
      POSTGRES_PASSWORD: ${USER_PGPASSWORD}
      POSTGRES_DB: ${USER_PGDATABASE}
    networks:
      - mon-network
    volumes:
      - user-local_pgdata:/var/lib/postgresql/data

  user_pgadmin:
    image: dpage/pgadmin4
    container_name: user-pgadmin4
    restart: unless-stopped
    ports:
      - "9888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.user
      PGADMIN_DEFAULT_PASSWORD: user
    volumes:
      - user-pgadmin-data:/var/lib/pgadmin
    networks:
      - mon-network
    depends_on:
      - user_db

  front:
    image: node:18
    container_name: front-app
    working_dir: /app
    volumes:
      - ./front-app:/app
    networks:
      - mon-network
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - api_gateway

volumes:
  card-local_pgdata:
  card-pgadmin-data:
  user-local_pgdata:
  user-pgadmin-data:

networks:
  mon-network:
    driver: bridge
