version: '3.8'
services:
  user_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    networks:
      - mon-network
    depends_on:
      - user_db
    ports:
      - '9000:9000'
  user_db:
    image: postgres
    container_name: user_pgdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    networks:
      - mon-network
    volumes:
      - user-local_pgdata:/var/lib/postgresql
  user_pgadmin:
    image: dpage/pgadmin4
    container_name: user-pgadmin4
    restart: unless-stopped
    ports:
      - '9888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.user
      PGADMIN_DEFAULT_PASSWORD: user
    volumes:
      - user-pgadmin-data:/var/lib/pgadmin
    networks:
      - mon-network
    depends_on:
      - user_db

volumes:
  user-local_pgdata:
  user-pgadmin-data:

networks:
  mon-network:
    driver: bridge
    external: true